### ISSUE TITLE
Please provide your ICP wallet principal id & account id to receive the ETHKL 24 prize

### ISSUE THREAD

**Issue by onimusya** [Noobmaster169/local-dao#11]

**Comment by Noobmaster169** [comment]
Hello there, 
This is my ICP Account

Principal ID:
bmves-4s62h-77qbf-hvubl-a3rzh-pp6et-c3qss-aixlp-itavp-ks63v-wae
Account ID:
4eaa547f028631674b424b4e44ec5bd5ee486b6f132d70de7ad8cb3a9476f3d7

Thank you, sorry for the delay

**Comment by Noobmaster169** [comment]
Hello there,
This is my ICP Account

Principal ID:
bmves-4s62h-77qbf-hvubl-a3rzh-pp6et-c3qss-aixlp-itavp-ks63v-wae
Account ID:
4eaa547f028631674b424b4e44ec5bd5ee486b6f132d70de7ad8cb3a9476f3d7

Thank you, sorry for the delay
